import { PrismaClient } from "../src/generated/prisma";

const prisma = new PrismaClient();

function slugify(t: string) {
  return t.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}
function makeSku(brand: string, name: string) {
  return `${brand.toUpperCase().replace(/[^A-Z0-9]/g, "").slice(0, 8)}-${name.toUpperCase().replace(/[^A-Z0-9]/g, "").slice(0, 12)}-10ML`;
}
function rand(min: number, max: number) { return Math.floor(Math.random() * (max - min + 1)) + min; }

const products = [
  { brand: "Chanel", name: "No 5", c: "EDP", sf: "Floral", p: 499, top: "Aldehyder, ylang ylang", mid: "Iris, rose", base: "Sandalwood, vetiver", desc: "Den ikoniska parfymen – tidlös feminin elegans." },
  { brand: "Chanel", name: "Coco Mademoiselle", c: "EDP", sf: "Oriental", p: 549, top: "Orange, bergamot", mid: "Rose, jasmine", base: "Patchouli, musk", desc: "Frisk orientalisk doft med sensuell touch." },
  { brand: "Chanel", name: "Chance", c: "EDT", sf: "Floral", p: 479, top: "Citrus, pink pepper", mid: "Jasmine, iris", base: "Patchouli, white musk", desc: "Mjuk blommig doft med modern twist." },
  { brand: "Chanel", name: "Bleu de Chanel", c: "EDP", sf: "Woody", p: 529, top: "Grapefruit, mint", mid: "Ginger, jasmine", base: "Sandalwood, cedar", desc: "Djärv träig aromatisk herrdoft." },
  { brand: "Chanel", name: "Allure", c: "EDP", sf: "Oriental", p: 509, top: "Mandarin, coriander", mid: "Rose, jasmine", base: "Vetiver, vanilla, musk", desc: "Mjuk alluring orientalisk feminin doft." },
  { brand: "Dior", name: "Jadore", c: "EDP", sf: "Floral", p: 519, top: "Pear, bergamot", mid: "Rose, jasmine, lily", base: "Sandalwood, musk", desc: "Feminin lyxig bukett av vita blommor." },
  { brand: "Dior", name: "Sauvage", c: "EDT", sf: "Fresh", p: 499, top: "Bergamot, pepper", mid: "Lavender, vetiver", base: "Ambroxan, cedar", desc: "Råhet och finhet i perfekt balans." },
  { brand: "Dior", name: "Miss Dior", c: "EDP", sf: "Floral", p: 489, top: "Bergamot, pink pepper", mid: "Rose, peony", base: "Patchouli, musk", desc: "Blommig frisk sensuell Dior-doft." },
  { brand: "Dior", name: "Fahrenheit", c: "EDT", sf: "Woody", p: 459, top: "Lavender, lemon", mid: "Cedar, hawthorn", base: "Leather, vetiver", desc: "Djärv maskulin klassiker med läder." },
  { brand: "Dior", name: "Joy", c: "EDP", sf: "Floral", p: 479, top: "Bergamot, mandarin", mid: "Rose, gardenia", base: "Sandalwood, musk", desc: "Ode till glädjen med franska Grasse-rosor." },
  { brand: "Yves Saint Laurent", name: "Black Opium", c: "EDP", sf: "Gourmand", p: 519, top: "Pink pepper, pear", mid: "Coffee, jasmine", base: "Patchouli, vanilla", desc: "Adrenalinkick av kaffe och vita blommor." },
  { brand: "Yves Saint Laurent", name: "Libre", c: "EDP", sf: "Floral", p: 529, top: "Lavender, mandarin", mid: "Orange blossom", base: "Musk, vanilla", desc: "Fri feminin doft med lavendel och apelsinblomma." },
  { brand: "Yves Saint Laurent", name: "Mon Paris", c: "EDP", sf: "Floral", p: 489, top: "Raspberry, strawberry", mid: "Rose, peony", base: "Patchouli, musk", desc: "Parisisk doft med bär och blommor." },
  { brand: "Yves Saint Laurent", name: "Opium", c: "EDP", sf: "Oriental", p: 469, top: "Plum, pepper", mid: "Rose, clove", base: "Sandalwood, incense", desc: "Legendarisk sensuell orientalisk doft." },
  { brand: "Gucci", name: "Bloom", c: "EDP", sf: "Floral", p: 489, top: "Tuberose", mid: "Jasmine, rangoon creeper", base: "Sandalwood, musk", desc: "Intensivt blommig trädgårdsdoft." },
  { brand: "Gucci", name: "Guilty", c: "EDP", sf: "Oriental", p: 499, top: "Pink pepper, mandarin", mid: "Rose, geranium", base: "Patchouli, musk", desc: "Sensuell och modig orientalisk doft." },
  { brand: "Gucci", name: "Flora Gorgeous Gardenia", c: "EDT", sf: "Floral", p: 449, top: "Red berries, pear", mid: "Gardenia, frangipani", base: "Patchouli, brown sugar", desc: "Frisk feminin gardenia-doft." },
  { brand: "Tom Ford", name: "Black Orchid", c: "EDP", sf: "Oriental", p: 649, top: "Truffle, gardenia", mid: "Orchid, dark chocolate", base: "Patchouli, sandalwood", desc: "Djup mystisk blomsterdoft med mörk lyx." },
  { brand: "Tom Ford", name: "Tobacco Vanille", c: "EDP", sf: "Oriental", p: 699, top: "Tobacco leaf, spices", mid: "Tobacco blossom, jasmine", base: "Vanilla, cacao", desc: "Rik välkryddad tobak-vaniljdoft." },
  { brand: "Tom Ford", name: "Oud Wood", c: "EDP", sf: "Woody", p: 749, top: "Oud wood, cardamom", mid: "Sandalwood, vetiver", base: "Tonka bean, amber", desc: "Sällsynt exotisk oud-doft." },
  { brand: "Tom Ford", name: "Neroli Portofino", c: "EDT", sf: "Fresh", p: 629, top: "Sicilian lemon, mandarin", mid: "Neroli, jasmine", base: "Ambergris, oakmoss", desc: "Uppfriskande mediterran citrondoft." },
  { brand: "Tom Ford", name: "Lost Cherry", c: "EDP", sf: "Oriental", p: 699, top: "Cherry, bitter almond", mid: "Turkish rose, jasmine", base: "Tonka bean, vanilla", desc: "Förtrollande körsbärsdoft med mörkt djup." },
  { brand: "Jo Malone", name: "Lime Basil and Mandarin", c: "EDC", sf: "Fresh", p: 579, top: "Lime, mandarin, basil", mid: "Thyme", base: "Patchouli, vetiver", desc: "Jo Malones signaturdoft – frisk aromatisk citrus." },
  { brand: "Jo Malone", name: "Wood Sage and Sea Salt", c: "EDC", sf: "Aquatic", p: 549, top: "Sea salt", mid: "Sage", base: "Driftwood, musk", desc: "Kustnära sensation av havsluft." },
  { brand: "Jo Malone", name: "English Pear and Freesia", c: "EDC", sf: "Floral", p: 559, top: "Pear, melon", mid: "Freesia, rhubarb", base: "Patchouli, amber", desc: "Höstlandskapet i en flaska." },
  { brand: "Jo Malone", name: "Peony and Blush Suede", c: "EDC", sf: "Floral", p: 579, top: "Red apple, pear", mid: "Peony, rose, jasmine", base: "Suede, amber musk", desc: "Romantisk feminin pion och mocka." },
  { brand: "Creed", name: "Aventus", c: "EDP", sf: "Fresh", p: 799, top: "Pineapple, bergamot, apple", mid: "Birch, rose, jasmine", base: "Musk, oakmoss, vanilla", desc: "Legendärisk herrparfym som hyllar framgång." },
  { brand: "Creed", name: "Millesime Imperial", c: "EDP", sf: "Aquatic", p: 749, top: "Lemon, bergamot, sea notes", mid: "Iris, cardamom", base: "Musk, ambra", desc: "Kunglig marint inspirerad doft." },
  { brand: "Creed", name: "Green Irish Tweed", c: "EDP", sf: "Fresh", p: 699, top: "Violet leaf, iris, verbena", mid: "Sandalwood, florals", base: "Ambergris, oakmoss", desc: "Frisk grön irländsk landskap-doft." },
  { brand: "Versace", name: "Bright Crystal", c: "EDT", sf: "Floral", p: 399, top: "Pomegranate, yuzu, lotus", mid: "Magnolia, peony", base: "Amber, mahogany, musk", desc: "Ljus kristallklar feminin doft." },
  { brand: "Versace", name: "Eros", c: "EDT", sf: "Fresh", p: 419, top: "Mint, apple, lemon", mid: "Tonka bean, geranium", base: "Vetiver, oakmoss", desc: "Stark modern maskulin klassiker." },
  { brand: "Versace", name: "Dylan Blue", c: "EDP", sf: "Aquatic", p: 429, top: "Grapefruit, fig leaf", mid: "Violet leaf, patchouli", base: "Tonka bean, musk", desc: "Djup sofistikerad akvatisk herrdoft." },
  { brand: "Versace", name: "Crystal Noir", c: "EDP", sf: "Oriental", p: 409, top: "Ginger, cardamom", mid: "Gardenia, coconut", base: "Amber, sandalwood", desc: "Mörk mystisk feminin orientalisk doft." },
  { brand: "Calvin Klein", name: "CK One", c: "EDT", sf: "Fresh", p: 299, top: "Pineapple, mandarin", mid: "Violet, rose", base: "Amber, musk, sandalwood", desc: "Ikonisk unisexparfym från 1994." },
  { brand: "Calvin Klein", name: "Eternity", c: "EDP", sf: "Floral", p: 349, top: "Freesia, lemon", mid: "White lily, violet", base: "Sandalwood, amber", desc: "Romantisk tidlös doft." },
  { brand: "Calvin Klein", name: "Obsession", c: "EDP", sf: "Oriental", p: 329, top: "Mandarin, bergamot", mid: "Jasmine, rose", base: "Amber, musk", desc: "Intensiv sensuell orientalisk doft." },
  { brand: "Calvin Klein", name: "Euphoria", c: "EDP", sf: "Oriental", p: 369, top: "Black orchid, pomegranate", mid: "Champaca, violet", base: "Mahogany, musk", desc: "Sensuell modern orientalisk doft." },
  { brand: "Hugo Boss", name: "Boss Bottled", c: "EDT", sf: "Woody", p: 379, top: "Apple, plum, bergamot", mid: "Cinnamon, carnation", base: "Sandalwood, vetiver", desc: "Mjuk välbalanserad maskulin doft." },
  { brand: "Hugo Boss", name: "Hugo Man", c: "EDT", sf: "Fresh", p: 339, top: "Apple, pine, juniper", mid: "Geranium, mint", base: "Oakmoss, musk", desc: "Frisk livfull herrdoft." },
  { brand: "Hugo Boss", name: "The Scent", c: "EDT", sf: "Oriental", p: 389, top: "Ginger, maninka", mid: "Osmanthus", base: "Leather, amber", desc: "Magnetisk förförande doft." },
  { brand: "Hugo Boss", name: "Boss Alive", c: "EDP", sf: "Floral", p: 399, top: "Pineapple, bergamot", mid: "Jasmine, rose", base: "Sandalwood, vanilla", desc: "Frisk blommig feminin doft." },
  { brand: "Paco Rabanne", name: "1 Million", c: "EDT", sf: "Oriental", p: 429, top: "Grapefruit, mint, mandarin", mid: "Rose, cinnamon", base: "Leather, amber, patchouli", desc: "Äkta lyx i ett gyllene flakon." },
  { brand: "Paco Rabanne", name: "Lady Million", c: "EDP", sf: "Floral", p: 449, top: "Raspberry, neroli", mid: "Jasmine, orange blossom", base: "Patchouli, honey", desc: "Feminin lyxig blomsterdoft." },
  { brand: "Paco Rabanne", name: "Invictus", c: "EDT", sf: "Aquatic", p: 409, top: "Grapefruit, sea notes", mid: "Bay laurel, jasmine", base: "Guaiac wood, ambergris", desc: "Sportig frisk akvatisk herrdoft." },
  { brand: "Paco Rabanne", name: "Olympea", c: "EDP", sf: "Floral", p: 429, top: "Green mandarin, grapefruit", mid: "Jasmine, white tea", base: "Vanilla, sandalwood", desc: "Modern gudinnedoft." },
  { brand: "Paco Rabanne", name: "Fame", c: "EDP", sf: "Floral", p: 459, top: "Mango, plum", mid: "Jasmine, tuberose", base: "Musk, sandalwood", desc: "Ikonisk feminin doft med tropisk frukt." },
  { brand: "Giorgio Armani", name: "Acqua di Gio", c: "EDT", sf: "Aquatic", p: 449, top: "Sea, bergamot", mid: "Rosemary, freesia", base: "Cedar, amber, musk", desc: "Klassisk akvatisk Medelhavsälskad herrdoft." },
  { brand: "Giorgio Armani", name: "Si", c: "EDP", sf: "Floral", p: 489, top: "Blackcurrant, freesia", mid: "Rose, neroli", base: "Vanilla, ambergris", desc: "Elegant sofistikerad feminin doft." },
  { brand: "Giorgio Armani", name: "My Way", c: "EDP", sf: "Floral", p: 509, top: "Bergamot, orange blossom", mid: "Jasmine, tuberose", base: "Vanilla, cedar", desc: "Feminin doft som hyllar öppenhet." },
  { brand: "Burberry", name: "Her", c: "EDP", sf: "Fruity", p: 399, top: "Strawberry, blackcurrant", mid: "Jasmine, violet", base: "Musk, amber", desc: "Levande feminin Londoninspirerad doft." },
  { brand: "Burberry", name: "Mr Burberry", c: "EDT", sf: "Woody", p: 369, top: "Bergamot, mint", mid: "Birch, sage", base: "Vetiver, sandalwood, oakmoss", desc: "Sofistikerad brittisk maskulin doft." },
  { brand: "Givenchy", name: "LInterdit", c: "EDP", sf: "Floral", p: 479, top: "White flowers, orange", mid: "Tuberose, jasmine", base: "Patchouli, musk", desc: "Djärv modern feminin doft." },
  { brand: "Givenchy", name: "Gentleman Only", c: "EDT", sf: "Woody", p: 409, top: "Pink pepper, ginger", mid: "Iris, rose", base: "Patchouli, vetiver", desc: "Stilren maskulin gentleman-doft." },
  { brand: "Valentino", name: "Donna Born in Roma", c: "EDP", sf: "Oriental", p: 489, top: "Bergamot, vanilla", mid: "Jasmine, bourbon vanilla", base: "Musk, vanilla", desc: "Modern sofistikerad feminin doft." },
  { brand: "Valentino", name: "Voce Viva", c: "EDP", sf: "Floral", p: 499, top: "Bergamot, pear", mid: "Orange blossom, rose", base: "Musk, sandalwood", desc: "Levande fri feminin doft." },
  { brand: "Lancôme", name: "La Vie Est Belle", c: "EDP", sf: "Gourmand", p: 479, top: "Black currant, pear", mid: "Iris, jasmine", base: "Praline, vanilla", desc: "Njutbar doft som hyllar lyckan i livet." },
  { brand: "Lancôme", name: "Tresor", c: "EDP", sf: "Floral", p: 449, top: "Apricot, rose", mid: "Peach, iris", base: "Sandalwood, amber", desc: "Romantisk feminin doft." },
  { brand: "Lancôme", name: "Idole", c: "EDP", sf: "Floral", p: 459, top: "Bergamot, pear", mid: "Rose, lily of the valley", base: "Musk, woods", desc: "Modern progressiv feminin doft." },
  { brand: "Hermès", name: "Twilly dHermes", c: "EDP", sf: "Floral", p: 549, top: "Ginger, tuberose", mid: "Rose", base: "Sandalwood, vetiver", desc: "Ung sprallig feminin doft." },
  { brand: "Hermès", name: "Terre dHermes", c: "EDT", sf: "Woody", p: 529, top: "Orange, grapefruit", mid: "Pepper, pelargonium", base: "Cedar, vetiver", desc: "Djärv jordnära maskulin doft." },
  { brand: "Dolce and Gabbana", name: "Light Blue", c: "EDT", sf: "Fresh", p: 389, top: "Sicilian lemon, apple", mid: "Bamboo, jasmine", base: "Cedarwood, amber", desc: "Solbely st medelhavsdoft." },
  { brand: "Dolce and Gabbana", name: "The One", c: "EDP", sf: "Oriental", p: 429, top: "Mandarin, bergamot", mid: "Jasmine, lily, rose", base: "Amber, vanilla", desc: "Sensuell orientalisk doft." },
  { brand: "Jimmy Choo", name: "Jimmy Choo", c: "EDP", sf: "Floral", p: 359, top: "Pear, bergamot", mid: "Tiare flower, orchid", base: "Patchouli, suede", desc: "Feminin sensuell exotisk blomsterdoft." },
  { brand: "Marc Jacobs", name: "Daisy", c: "EDT", sf: "Floral", p: 369, top: "Strawberry, violet", mid: "Gardenia, jasmine", base: "Musk, vanilla", desc: "Ung frisk blommig doft." },
  { brand: "Marc Jacobs", name: "Honey", c: "EDP", sf: "Floral", p: 379, top: "Pear, nectarine", mid: "Peach, jasmine", base: "Honey, vanilla", desc: "Söt fruktblommig honungsdoft." },
  { brand: "Viktor and Rolf", name: "Flowerbomb", c: "EDP", sf: "Floral", p: 519, top: "Tea, bergamot", mid: "Jasmine, rose, orchid", base: "Patchouli, amber", desc: "Explosiv blombomb." },
  { brand: "Viktor and Rolf", name: "Spicebomb", c: "EDT", sf: "Aromatic", p: 489, top: "Bergamot, pink pepper", mid: "Saffron, cinnamon", base: "Vetiver, leather", desc: "Kryddig maskulin doft." },
  { brand: "Narciso Rodriguez", name: "For Her", c: "EDP", sf: "Floral", p: 439, top: "Rose, jasmine", mid: "Musk, amber", base: "Vetiver, sandalwood", desc: "Minimalistisk sensuell feminin doft." },
  { brand: "Issey Miyake", name: "LEau dIssey", c: "EDT", sf: "Aquatic", p: 359, top: "Cyclamen, yuzu", mid: "Lotus", base: "Musk, cedar", desc: "Ikonisk ren akvatisk feminin doft." },
  { brand: "Issey Miyake", name: "LEau dIssey Pour Homme", c: "EDT", sf: "Aquatic", p: 369, top: "Yuzu, lemon", mid: "Cinnamon, sage", base: "Vetiver, wood", desc: "Maritim maskulin akvatisk doft." },
  { brand: "Davidoff", name: "Cool Water", c: "EDT", sf: "Aquatic", p: 299, top: "Aquatics, mint", mid: "Lavender, jasmine", base: "Sandalwood, musk", desc: "Klassisk akvatisk maskulin doft sedan 1988." },
  { brand: "DKNY", name: "Be Delicious", c: "EDP", sf: "Fresh", p: 369, top: "Green apple, cucumber", mid: "Magnolia, rose", base: "Sandalwood, amber", desc: "Frisk New York-inspirerad doft." },
  { brand: "Jean Paul Gaultier", name: "Classique", c: "EDT", sf: "Oriental", p: 409, top: "Bergamot, rose", mid: "Orange blossom, vanilla", base: "Amber, musk", desc: "Ikonisk feminin doft i korsettflaskan." },
  { brand: "Jean Paul Gaultier", name: "Le Male", c: "EDT", sf: "Aromatic", p: 399, top: "Mint, lavender", mid: "Orange blossom, cinnamon", base: "Vanilla, amber", desc: "Maskulin klassiker med lavendel och vanilj." },
  { brand: "Ralph Lauren", name: "Romance", c: "EDP", sf: "Floral", p: 379, top: "Calla lily, freesia", mid: "Rose, iris", base: "Sandalwood, musk", desc: "Romantisk tidlös feminin doft." },
  { brand: "Ralph Lauren", name: "Polo Blue", c: "EDT", sf: "Aquatic", p: 369, top: "Cantaloupe, cucumber", mid: "Sage, basil", base: "Suede, musk", desc: "Luftig frisk maskulin havsluftsdoft." },
  { brand: "Byredo", name: "Bal dAfrique", c: "EDP", sf: "Floral", p: 649, top: "Bergamot, cedarwood", mid: "Neroli, violet", base: "Musk, amber", desc: "Paris med afrikanska doftinfluenser." },
  { brand: "Byredo", name: "Gypsy Water", c: "EDP", sf: "Woody", p: 629, top: "Bergamot, pepper", mid: "Juniper, incense", base: "Amber, sandalwood", desc: "Frihetsdoft inspirerad av zigenarlivsstilen." },
  { brand: "Byredo", name: "Blanche", c: "EDP", sf: "Floral", p: 599, top: "Aldehyde, pink pepper", mid: "Rose, peony", base: "Sandalwood, musk", desc: "Ren himmelskt vit aldehyddoft." },
  { brand: "Byredo", name: "Mojave Ghost", c: "EDP", sf: "Woody", p: 639, top: "Ambrette", mid: "Violet, magnolia", base: "Sandalwood, musk", desc: "Ökenblomma i fullmånens ljus." },
  { brand: "Le Labo", name: "Santal 33", c: "EDP", sf: "Woody", p: 699, top: "Cardamom, iris", mid: "Cedarwood", base: "Sandalwood, leather, musk", desc: "Kultparfymen – sandelträ och läder." },
  { brand: "Le Labo", name: "Rose 31", c: "EDP", sf: "Floral", p: 679, top: "Cedar, rose", mid: "Rose absolute, laurel", base: "Musk, amber", desc: "Sofistikerad rosendoft med kryddig komplexitet." },
  { brand: "Le Labo", name: "Another 13", c: "EDP", sf: "Woody", p: 729, top: "Ambrox, jasmine", mid: "Musk", base: "Musk, ambergris", desc: "Ikonisk unisex musk-doft." },
  { brand: "Maison Margiela", name: "Replica Jazz Club", c: "EDT", sf: "Woody", p: 549, top: "Rum, pink pepper", mid: "Vetiver, clary sage", base: "Tonka bean, vanilla", desc: "Minnet av en New York jazzklubb." },
  { brand: "Maison Margiela", name: "Replica Beach Walk", c: "EDT", sf: "Fresh", p: 529, top: "Bergamot, ylang ylang", mid: "Coconut milk, jasmine", base: "Musk, sandalwood", desc: "Den perfekta stranddagen i en flaska." },
  { brand: "Maison Margiela", name: "Replica Flower Market", c: "EDT", sf: "Floral", p: 539, top: "Peony, lily", mid: "White rose, jasmine", base: "Vetiver, musk", desc: "Promenad genom ett sommarblommigt torg." },
  { brand: "Diptyque", name: "Eau Rose", c: "EDT", sf: "Floral", p: 549, top: "Peony, grapefruit", mid: "Rose", base: "Musk, woody notes", desc: "Modernt blommig rosinterpretation." },
  { brand: "Diptyque", name: "Philosykos", c: "EDT", sf: "Woody", p: 529, top: "Green fig, fig leaves", mid: "Fig wood", base: "White cedar", desc: "Ode till fikonträdet." },
  { brand: "Acqua di Parma", name: "Colonia", c: "EDC", sf: "Citrus", p: 579, top: "Bergamot, lemon, orange", mid: "Lavender, rosemary", base: "Iris, sandalwood", desc: "Italiensk elegans i sin renaste form." },
  { brand: "Amouage", name: "Interlude Man", c: "EDP", sf: "Woody", p: 749, top: "Bergamot, oregano", mid: "Incense, amber", base: "Agarwood, sandalwood", desc: "Komplex maskulin rök och kryddor." },
  { brand: "Parfums de Marly", name: "Delina", c: "EDP", sf: "Floral", p: 699, top: "Rhubarb, lychee", mid: "Turkish rose, peony", base: "Musk, vanilla", desc: "Magnifik feminin Versailles-doft." },
  { brand: "Parfums de Marly", name: "Layton", c: "EDP", sf: "Aromatic", p: 679, top: "Apple, lavender", mid: "Jasmine, violet", base: "Vanilla, sandalwood", desc: "Sofistikerad maskulin lavendelkryddor-doft." },
  { brand: "Initio", name: "Oud for Greatness", c: "EDP", sf: "Woody", p: 749, top: "Saffron, cardamom", mid: "Oud, davana", base: "Sandalwood, ambergris", desc: "Storslaget intensiv oud-doft." },
  { brand: "Penhaligons", name: "Halfeti", c: "EDP", sf: "Oriental", p: 649, top: "Bergamot, rose", mid: "Jasmine, oud", base: "Sandalwood, ambra", desc: "Mystisk turkisk by-inspirerad doft." },
  { brand: "Frederic Malle", name: "Portrait of a Lady", c: "EDP", sf: "Oriental", p: 749, top: "Raspberry, blackcurrant", mid: "Turkish rose, patchouli", base: "Sandalwood, incense", desc: "Mästerverk av ros och patchouli." },
  { brand: "Maison Francis Kurkdjian", name: "Baccarat Rouge 540", c: "EDP", sf: "Floral", p: 799, top: "Jasmine, saffron", mid: "Amberwood, ambergris", base: "Fir resin, cedarwood", desc: "Ikonisk modern doft med saffran och jasmin." },
  { brand: "Elie Saab", name: "Le Parfum", c: "EDP", sf: "Floral", p: 429, top: "Orange blossom, jasmine", mid: "Rose, jasmine", base: "Patchouli, honey", desc: "Romantisk lyxig feminin doft." },
  { brand: "Chloe", name: "Chloe", c: "EDP", sf: "Floral", p: 399, top: "Peony, freesia, lychee", mid: "Rose, magnolia", base: "Cedar, sandalwood", desc: "Modern feminin rosendoft." },
  { brand: "Thierry Mugler", name: "Angel", c: "EDP", sf: "Gourmand", p: 429, top: "Fruity, hedione", mid: "Honey, caramel, jasmine", base: "Vanilla, chocolate", desc: "Ikonisk gourmand-doft i stjärnflaska." },
  { brand: "Thierry Mugler", name: "Alien", c: "EDP", sf: "Floral", p: 419, top: "Jasmine, lily", mid: "Sambac jasmine", base: "White amber, wood", desc: "Mystisk kraftfull jasmin-doft." },
  { brand: "Kenzo", name: "Flower by Kenzo", c: "EDP", sf: "Floral", p: 359, top: "White anemone, rose", mid: "Parma violet, rose", base: "White musk, vanilla", desc: "Poetisk blomsterdoft inspirerad av vallmo." },
  { brand: "Carolina Herrera", name: "Good Girl", c: "EDP", sf: "Gourmand", p: 459, top: "Almond, coffee", mid: "Tuberose, jasmine", base: "Tonka bean, cacao", desc: "Söt sensuell doft med kaffe och tuberose." },
  { brand: "Carolina Herrera", name: "212 VIP", c: "EDP", sf: "Floral", p: 429, top: "Gardenia, musk", mid: "White flowers", base: "Musk, sandalwood", desc: "Urban exklusiv feminin doft." },
  { brand: "Guerlain", name: "Mon Guerlain", c: "EDP", sf: "Oriental", p: 459, top: "Bergamot, lavender", mid: "Lavender, peony", base: "Vanilla, sandalwood", desc: "Feminin lavendeldoft med franska accenter." },
  { brand: "Guerlain", name: "Shalimar", c: "EDP", sf: "Oriental", p: 479, top: "Bergamot, lemon", mid: "Rose, jasmine", base: "Vanilla, opoponax", desc: "Klassisk orientalisk doft sedan 1925." },
  { brand: "Prada", name: "Candy", c: "EDP", sf: "Gourmand", p: 449, top: "Caramel, benzoin", mid: "Benzoin, musk", base: "Vanilla, musk", desc: "Söt sensuell karamell och vanilj." },
  { brand: "Prada", name: "La Femme", c: "EDP", sf: "Floral", p: 469, top: "Bergamot, neroli", mid: "Tuberose, jasmine", base: "Sandalwood, vanilla", desc: "Elegant modernt feminin doft." },
  { brand: "Montblanc", name: "Legend", c: "EDT", sf: "Fresh", p: 309, top: "Bergamot, lavandin", mid: "Geranium, rose", base: "Sandalwood, oakmoss", desc: "Maskulin doft som hyllar äventyret." },
  { brand: "Montblanc", name: "Explorer", c: "EDP", sf: "Woody", p: 329, top: "Bergamot, pink pepper", mid: "Iso E super", base: "Patchouli, sandalwood", desc: "Modern äventyrsmaskulin doft." },
  { brand: "Bvlgari", name: "Aqva Pour Homme", c: "EDT", sf: "Aquatic", p: 359, top: "Mandarin, wood", mid: "Cistus, galbanum", base: "Amber, musk", desc: "Djup marin maskulin doft." },
  { brand: "Clinique", name: "Happy", c: "EDP", sf: "Citrus", p: 319, top: "Grapefruit, orange blossom", mid: "Freesia, lily", base: "Amber, musk", desc: "Lycklig optimistisk citrusdoft." },
  { brand: "Azzaro", name: "Chrome", c: "EDT", sf: "Aquatic", p: 299, top: "Bergamot, rosemary", mid: "Cardamom, jasmine", base: "Cedarwood, musk", desc: "Klassisk sportig maskulin doft." },
  { brand: "Salvatore Ferragamo", name: "Signorina", c: "EDP", sf: "Floral", p: 339, top: "Peach, bergamot", mid: "Rose, jasmine", base: "Patchouli, amber", desc: "Lyxig feminin doft med italiensk elegans." },
  { brand: "Cartier", name: "La Panthere", c: "EDP", sf: "Chypre", p: 449, top: "Gardenia, musk", mid: "Oakmoss, sandalwood", base: "Amber, musk", desc: "Djärvt feminin panterinspirerad doft." },
  { brand: "Bottega Veneta", name: "Bottega Veneta", c: "EDP", sf: "Chypre", p: 499, top: "Bergamot, raspberry", mid: "Rose, peony", base: "Leather, oakmoss", desc: "Modern sofistikerad chypre-doft." },
  { brand: "Nina Ricci", name: "LAir du Temps", c: "EDT", sf: "Floral", p: 299, top: "Gardenia, bergamot", mid: "Rose, iris", base: "Musk, sandalwood", desc: "Tidlös romantisk doft sedan 1948." },
  { brand: "Moschino", name: "Cheap and Chic", c: "EDT", sf: "Floral", p: 309, top: "Rose, jasmine", mid: "Jasmine, rose", base: "Sandalwood, musk", desc: "Lekfull feminin doft som blandar mode med humor." },
  { brand: "Lolita Lempicka", name: "Lolita Lempicka", c: "EDP", sf: "Oriental", p: 329, top: "Anise, licorice", mid: "Iris, amarena cherry", base: "Vanilla, tonka bean", desc: "Magisk mystisk aniskörsbärsdoft." },
  { brand: "Cacharel", name: "Amor Amor", c: "EDP", sf: "Floral", p: 289, top: "Orange, blackcurrant", mid: "Rose, jasmine", base: "Vanilla, amber", desc: "Passionerad ung kärleksdoft." },
  { brand: "Jil Sander", name: "Simply", c: "EDP", sf: "Floral", p: 299, top: "Freesia, bergamot", mid: "Rose, peony", base: "Sandalwood, musk", desc: "Enkel elegant minimalistisk doft." },
  { brand: "Serge Lutens", name: "La Fille de Berlin", c: "EDP", sf: "Floral", p: 549, top: "Pepper, rose", mid: "Rose", base: "Rose, musk", desc: "Ren rosendoft med metallisk skärpa." },
  { brand: "Loewe", name: "Esencia", c: "EDT", sf: "Woody", p: 389, top: "Artemisia, neroli", mid: "Rose, viola", base: "Sandalwood, benzoin", desc: "Klassisk spansk maskulin doft." },
  { brand: "Escada", name: "Especially Escada", c: "EDP", sf: "Floral", p: 319, top: "Peach", mid: "Peony, jasmine", base: "Musk, sandalwood", desc: "Feminin kärleksfull blomsterdoft." },
  { brand: "Vera Wang", name: "Princess", c: "EDT", sf: "Floral", p: 289, top: "Water lily, apricot", mid: "Peach, guava, jasmine", base: "Amber, woods", desc: "Ung frisk feminin doft." },
  { brand: "Stella McCartney", name: "Stella", c: "EDP", sf: "Floral", p: 349, top: "Peony, pear", mid: "Ambrosial rose", base: "Sandalwood, amber", desc: "Ren feminin naturlig rosendoft." },
  { brand: "Chopard", name: "Wish", c: "EDP", sf: "Oriental", p: 299, top: "Peach, mango", mid: "Lotus, heliotrope", base: "Sandalwood, vanilla", desc: "Söt drömlik feminin doft." },
  { brand: "Agent Provocateur", name: "Agent Provocateur", c: "EDP", sf: "Oriental", p: 329, top: "Rose, coriander", mid: "Jasmine, tuberose", base: "Musk, sandalwood", desc: "Sensuell djärvt feminin doft." },
  { brand: "Lanvin", name: "Eclat de Fleurs", c: "EDT", sf: "Floral", p: 299, top: "Peach, bergamot", mid: "Rose, magnolia", base: "Musk, amber", desc: "Ljus feminin persikablomsterdoft." },
  { brand: "Cerruti", name: "1881 Pour Homme", c: "EDT", sf: "Aromatic", p: 279, top: "Bergamot, lavender", mid: "Jasmine, geranium", base: "Sandalwood, oakmoss", desc: "Klassisk aromatisk maskulin doft." },
  { brand: "Dunhill", name: "Icon Elite", c: "EDP", sf: "Woody", p: 309, top: "Bergamot, coriander", mid: "Tobacco, rosewood", base: "Sandalwood, musk", desc: "Maskulin tobak och träig doft." },
  { brand: "Estee Lauder", name: "White Linen", c: "EDP", sf: "Floral", p: 349, top: "Aldehydes, bergamot", mid: "Rose, iris", base: "Vetiver, sandalwood", desc: "Klassisk ren linjedoft." },
  { brand: "Ferrari", name: "Black", c: "EDT", sf: "Woody", p: 269, top: "Bergamot, citrus", mid: "Iris, cardamom", base: "Amber, sandalwood", desc: "Sportigt elegant maskulin doft." },
  { brand: "Lacoste", name: "Essential", c: "EDT", sf: "Aromatic", p: 319, top: "Bergamot, tomato leaves", mid: "Rose, cinnamon", base: "Patchouli, vetiver", desc: "Frisk aromatisk maskulin doft." },
  { brand: "Givenchy", name: "Irresistible", c: "EDP", sf: "Floral", p: 429, top: "Rose, peony", mid: "Freesia, litchi", base: "Sandalwood, musk", desc: "Oemotståndlig feminin doft." },
  { brand: "Christian Dior", name: "Hypnotic Poison", c: "EDT", sf: "Oriental", p: 469, top: "Almond, plum", mid: "Jasmine, coconut", base: "Musk, vanilla", desc: "Beroendeframkallande orientalisk doft." },
  { brand: "Prada", name: "Luna Rossa", c: "EDT", sf: "Aromatic", p: 419, top: "Bergamot, lavender", mid: "Sage, basil", base: "Ambrette, patchouli", desc: "Sportig modern aromatisk herrdoft." },
  { brand: "Bulgari", name: "Rose Goldea", c: "EDP", sf: "Floral", p: 399, top: "Peony, rose", mid: "May rose, tuberose", base: "Musk, amber", desc: "Lyxig blommig feminin rosendoft." },
  { brand: "Versace", name: "Pour Femme", c: "EDP", sf: "Floral", p: 399, top: "Bergamot, peach, tuberose", mid: "Peony, rose", base: "Slipper orchid, patchouli", desc: "Lyxig blommig Versace-doft." },
  { brand: "Azzaro", name: "Wanted", c: "EDT", sf: "Woody", p: 319, top: "Grapefruit, cardamom", mid: "Vetiver, star anise", base: "Tobacco, musk", desc: "Djärv äventyrlig maskulin doft." },
  { brand: "Hermès", name: "Un Jardin sur le Nil", c: "EDT", sf: "Fresh", p: 499, top: "Green mango, grapefruit", mid: "Lotus flower, tomato leaves", base: "Blue lotus, sycamore", desc: "Vacker trädgårdsdoft från Nilen." },
  { brand: "Chloe", name: "Nomade", c: "EDP", sf: "Chypre", p: 419, top: "Mirabelle plum, freesia", mid: "Oak moss, jasmine", base: "Oakmoss, amber", desc: "Äventyrskvinnans doft med ek och plommon." },
  { brand: "Lanvin", name: "Modern Princess", c: "EDP", sf: "Floral", p: 329, top: "Bergamot, pear", mid: "White almond, peony, rose", base: "Sandalwood, vanilla, musk", desc: "En modern prinsessdoft med delikata blommor." },
  { brand: "Montblanc", name: "Emblem", c: "EDT", sf: "Woody", p: 289, top: "Grapefruit, saffron", mid: "Leather, cedar", base: "Sandalwood, musk", desc: "En maskulin doft med läder och trä." },
  { brand: "Hugo Boss", name: "Ma Vie", c: "EDP", sf: "Floral", p: 359, top: "Peach, bergamot", mid: "Jasmine, rose, lily", base: "Sandalwood, musk", desc: "Frisk blommig feminin livsglädjesdoft." },
  { brand: "Paco Rabanne", name: "Black XS", c: "EDT", sf: "Oriental", p: 369, top: "Bergamot, pink pepper", mid: "Heliotrope, musk", base: "Leather, patchouli", desc: "En ungdomlig rockig maskulin doft." },
  { brand: "Davidoff", name: "Zino", c: "EDP", sf: "Woody", p: 319, top: "Lavender, bergamot", mid: "Rose, jasmine", base: "Sandalwood, oakmoss", desc: "Maskulin klassisk träig aromatisk doft." },
  { brand: "Escada", name: "Joyful", c: "EDP", sf: "Fruity", p: 299, top: "Raspberry, lychee", mid: "Peony, tuberose, jasmine", base: "Musk, sandalwood", desc: "Gladlynt feminin bär och blomsterdoft." },
  { brand: "Kenneth Cole", name: "Reaction", c: "EDT", sf: "Aromatic", p: 249, top: "Bergamot, grapefruit", mid: "Geranium, cardamom", base: "Sandalwood, vetiver", desc: "Frisk modern maskulin doft." },
  { brand: "Zara", name: "Rose Gold", c: "EDP", sf: "Floral", p: 199, top: "Rose, bergamot", mid: "Rose, jasmine", base: "Musk, sandalwood", desc: "Tillgänglig och elegantfeminin rosdoft." },
  { brand: "Zara", name: "Gardenia", c: "EDT", sf: "Floral", p: 179, top: "Gardenia, white musk", mid: "Jasmine, tuberose", base: "Sandalwood, musk", desc: "Frisk och blommig vardagsdoft." },
  // Additional products to reach 250+
  { brand: "Byredo", name: "Bal d'Afrique", c: "EDP", sf: "Floral", p: 699, top: "Neroli, bergamot", mid: "Violet, African marigold", base: "Musk, cedar, vetiver", desc: "Exotisk blommig doft inspirerad av Afrika." },
  { brand: "Byredo", name: "Gypsy Water", c: "EDP", sf: "Woody", p: 699, top: "Bergamot, lemon, pepper", mid: "Juniper berries, orris, pine needles", base: "Amber, sandalwood, vanilla", desc: "Mystisk och poetisk bohemisk doft." },
  { brand: "Byredo", name: "Mojave Ghost", c: "EDP", sf: "Woody", p: 699, top: "Ambrette, magnolia", mid: "Violet, sapodilla", base: "Sandalwood, cedarwood, musk", desc: "Öken inspirerad lätt träig doft." },
  { brand: "Byredo", name: "Rose of No Man's Land", c: "EDP", sf: "Floral", p: 699, top: "Pink pepper, papyrus", mid: "Turkish rose, rosewater", base: "Amber, white musk", desc: "Mjuk rosdoft med kryddig touch." },
  { brand: "Le Labo", name: "Santal 33", c: "EDP", sf: "Woody", p: 749, top: "Cardamom, iris, violet", mid: "Ambrox, papyrus", base: "Sandalwood, cedar, leather", desc: "Kultikonik sandelträdsdoft med läderaktig finish." },
  { brand: "Le Labo", name: "Rose 31", c: "EDP", sf: "Floral", p: 749, top: "Rose, cumin, lemon", mid: "Oud, cedar, vetiver", base: "Musk, amber, incense", desc: "Sofistikerad rosdoft med rökig träig bas." },
  { brand: "Le Labo", name: "Bergamote 22", c: "EDP", sf: "Citrus", p: 699, top: "Bergamot, citrus", mid: "Petitgrain, hedione", base: "Musk, amber, cedar", desc: "Frisk citrusprofil med varm träig bas." },
  { brand: "Maison Margiela", name: "Replica Jazz Club", c: "EDT", sf: "Woody", p: 549, top: "Pink pepper, neroli, lemon", mid: "Clary sage, rum", base: "Vanilla, woodsy notes, musk", desc: "Nostalgisk jazzbarsdoft – tobak och mörkt trä." },
  { brand: "Maison Margiela", name: "Replica Flower Market", c: "EDT", sf: "Floral", p: 529, top: "Rose, peony", mid: "Lily of valley, freesia", base: "Musk, woodsy notes", desc: "Levande blommarknadsupplevelse i en flaska." },
  { brand: "Maison Margiela", name: "Replica Beach Walk", c: "EDT", sf: "Fresh", p: 529, top: "Bergamot, lemon, pink pepper", mid: "Coconut, ylang ylang", base: "Cedar, musk, sandalwood", desc: "Sommardoft som för dig till stranden." },
  { brand: "Maison Margiela", name: "Replica By The Fireplace", c: "EDT", sf: "Gourmand", p: 549, top: "Pink pepper, orange, cloves", mid: "Chestnuts, guaiac wood", base: "Vanilla, cashmeran, musk", desc: "Varm och mysig kamineldoft." },
  { brand: "Diptyque", name: "Do Son", c: "EDT", sf: "Floral", p: 599, top: "Water tuberose, citrus", mid: "Tuberose, rose", base: "Musk, white cedar", desc: "Elegant tuberosedoft inspirerad av Vietnam." },
  { brand: "Diptyque", name: "Philosykos", c: "EDT", sf: "Woody", p: 599, top: "Fig leaf, green wood", mid: "Fig, sap", base: "White cedar, creamy fig wood", desc: "Träig figdoft – som att sitta under ett fikonträd." },
  { brand: "Diptyque", name: "Eau Rose", c: "EDT", sf: "Floral", p: 579, top: "Rose, lychee", mid: "Rose, magnolia", base: "Musk, white cedar", desc: "Frisk och feminin rosdoft." },
  { brand: "Frederic Malle", name: "Portrait of a Lady", c: "EDP", sf: "Oriental", p: 799, top: "Black pepper, pink pepper", mid: "Rose, patchouli", base: "Musk, sandalwood, incense", desc: "Stark och dramatisk rosdoft med orientalisk djup." },
  { brand: "Frederic Malle", name: "Carnal Flower", c: "EDP", sf: "Floral", p: 799, top: "Melon, eucalyptus", mid: "Tuberose, jasmine, ylang ylang", base: "Coconut, musk, vetiver", desc: "Extravagant och intens tuberosedoft." },
  { brand: "Acqua di Parma", name: "Colonia", c: "EDC", sf: "Citrus", p: 499, top: "Citrus, herbs", mid: "Rose, lavender", base: "Vetiver, sandalwood", desc: "Klassisk italiensk cologne – frisk och tidlös." },
  { brand: "Acqua di Parma", name: "Magnolia Nobile", c: "EDP", sf: "Floral", p: 549, top: "Magnolia, bergamot", mid: "Jasmine, ylang ylang", base: "Sandalwood, musk, amber", desc: "Elegant magnoliadoft – feminin och sofistikerad." },
  { brand: "Penhaligon's", name: "Empressa", c: "EDP", sf: "Oriental", p: 649, top: "Bergamot, orange blossom", mid: "Bulgarian rose, jasmine", base: "Vetiver, sandalwood, musk", desc: "Kunglig och sofistikerad orientalisk doft." },
  { brand: "Amouage", name: "Interlude", c: "EDP", sf: "Oriental", p: 799, top: "Bergamot, oregano, pepper", mid: "Labdanum, myrrh, incense", base: "Oud, sandalwood, leather", desc: "Komplex och djup orientalisk doft med rökiga toner." },
  { brand: "Parfums de Marly", name: "Delina", c: "EDP", sf: "Floral", p: 749, top: "Rhubarb, lychee", mid: "Turkish rose, peony, jasmine", base: "Musk, vanilla, cashmeran", desc: "Romantisk och feminin lyxdoft." },
  { brand: "Parfums de Marly", name: "Layton", c: "EDP", sf: "Aromatic", p: 749, top: "Apple, bergamot, lavender", mid: "Jasmine, geranium, violet", base: "Sandalwood, vanilla, musk", desc: "Elegant aromatisk herrdoft med sötma." },
  { brand: "Parfums de Marly", name: "Percival", c: "EDP", sf: "Woody", p: 749, top: "Bergamot, lemon, aldehydes", mid: "Vetiver, cedar, sandalwood", base: "Musk, amber, oakmoss", desc: "Djärv och maskulin träig doft." },
  { brand: "Initio", name: "Oud for Greatness", c: "EDP", sf: "Oriental", p: 799, top: "Nutmeg, saffron", mid: "Oud, jasmine", base: "Musk, patchouli", desc: "Intensiv oudbaserad orientalisk doft." },
  { brand: "Clive Christian", name: "X", c: "Parfum", sf: "Floral", p: 799, top: "Bergamot, cardamom", mid: "Rose, jasmine, ylang ylang", base: "Sandalwood, oud, musk", desc: "Exklusiv lyxparfym – en av världens dyraste." },
  { brand: "Roja Dove", name: "Enigma", c: "Parfum", sf: "Oriental", p: 799, top: "Grapefruit, aldehydes", mid: "Rose, jasmine, ylang ylang", base: "Oud, sandalwood, musk", desc: "Gåtfull och oförglömlig orientalisk lyxdoft." },
  { brand: "Viktor&Rolf", name: "Spicebomb Extreme", c: "EDP", sf: "Oriental", p: 429, top: "Black pepper, pink pepper", mid: "Tobacco, vetiver", base: "Vanilla, labdanum", desc: "Intensivare version av Spicebomb – varm och kryddig." },
  { brand: "Viktor&Rolf", name: "Good Fortune", c: "EDP", sf: "Floral", p: 399, top: "Ambrette, jasmine", mid: "Jasmine, iris", base: "Musk, sandalwood, patchouli", desc: "Optimistisk och modern blommig doft." },
  { brand: "Narciso Rodriguez", name: "Pure Musc", c: "EDP", sf: "Floral", p: 429, top: "Neroli", mid: "Rose, jasmine, orange blossom", base: "Musk, orris root", desc: "Mjuk och intim muskinspirerad doft." },
  { brand: "Narciso Rodriguez", name: "Amber Musc", c: "EDP", sf: "Oriental", p: 449, top: "Bergamot, pink pepper", mid: "Orange blossom, rose", base: "Amber, musk, vetiver", desc: "Varm och sensuell amberdoft." },
  { brand: "Issey Miyake", name: "L'Eau d'Issey", c: "EDT", sf: "Fresh", p: 349, top: "Lotus, cyclamen", mid: "Lily of valley, peony", base: "Musk, cedar, sandalwood", desc: "Ren och transparent waterdoft – klassiker." },
  { brand: "Issey Miyake", name: "L'Eau d'Issey Pour Homme", c: "EDT", sf: "Aquatic", p: 349, top: "Yuzu, calone, neroli", mid: "Coriander, lily of valley", base: "Sandalwood, vetiver, cedar", desc: "Frisk akvatisk maskulin doft." },
  { brand: "Issey Miyake", name: "Nectar d'Issey", c: "EDP", sf: "Fruity", p: 369, top: "Lychee, water melon", mid: "Jasmine, iris", base: "Amber, sandalwood, musk", desc: "Söt och fruktigt feminin sommarblomsterdoft." },
  { brand: "Davidoff", name: "Cool Water", c: "EDT", sf: "Aquatic", p: 249, top: "Peppermint, green herbs", mid: "Lavender, jasmine", base: "Sandalwood, musk, amber", desc: "Frisk klassisk akvatisk herrdoft." },
  { brand: "Davidoff", name: "Cool Water Woman", c: "EDT", sf: "Aquatic", p: 249, top: "Quince, pineapple", mid: "Aquatic notes, lotus", base: "Sandalwood, musk", desc: "Frisk och fruktig akvatisk damdoft." },
  { brand: "DKNY", name: "Be Delicious", c: "EDP", sf: "Fruity", p: 299, top: "Grapefruit, magnolia", mid: "Apple, violet, rose", base: "Sandalwood, amber, musk", desc: "Fruktigt urban New York-äppeldoft." },
  { brand: "DKNY", name: "My NY", c: "EDP", sf: "Floral", p: 319, top: "Pear, peach", mid: "Gardenia, orange blossom", base: "Sandalwood, amber, musk", desc: "Mjuk och urban feminin signaturblomsterdoft." },
  { brand: "Jean Paul Gaultier", name: "Le Beau Male", c: "EDT", sf: "Fresh", p: 349, top: "Mint, cardamom", mid: "Lavender, amber", base: "Vanilla, musk, cedar", desc: "Frisk sötaktig herrdoft med myntakick." },
  { brand: "Jean Paul Gaultier", name: "Classique Intense", c: "EDP", sf: "Oriental", p: 379, top: "Bergamot, orange blossom", mid: "Ylang ylang, rose", base: "Vanilla, amber, sandalwood", desc: "Sensuell intensiv version av ikonisk Le Male." },
  { brand: "Ralph Lauren", name: "Romance", c: "EDP", sf: "Floral", p: 349, top: "Chamomile, marigold", mid: "Rose, iris, lily", base: "Musk, patchouli, sandalwood", desc: "Romantisk och tidlös rosdoft." },
  { brand: "Ralph Lauren", name: "Polo Blue", c: "EDT", sf: "Aquatic", p: 329, top: "Cantaloupe, water", mid: "Basil, geranium", base: "Suede, oak, musk", desc: "Frisk akvatisk herrdoft – sportig elegans." },
  { brand: "Bottega Veneta", name: "Eau de Velours", c: "EDP", sf: "Woody", p: 499, top: "Bergamot, pear", mid: "Iris, rose", base: "Leather, sandalwood, musk", desc: "Lädrig och sofistikerad signaturdoft." },
  { brand: "Hermès", name: "Twilly d'Hermès", c: "EDP", sf: "Floral", p: 549, top: "Ginger, tuberose", mid: "Tuberose, rose", base: "Sandalwood, musk", desc: "Lekfull och kryddig blomsterdoft för den moderna kvinnan." },
  { brand: "Hermès", name: "Eau des Merveilles", c: "EDT", sf: "Oriental", p: 519, top: "Orange, petitgrain", mid: "Ambergris, woody notes", base: "Oak, white musk", desc: "Magisk doft med ambraaktig träig bas." },
  { brand: "Hermès", name: "Voyage d'Hermès", c: "EDT", sf: "Woody", p: 529, top: "Grapefruit, sage", mid: "Teak wood, jasmine", base: "Cedarwood, vetiver, white musk", desc: "Resans doft – frisk och fri." },
  { brand: "Dolce & Gabbana", name: "The One", c: "EDP", sf: "Oriental", p: 399, top: "Mandarin, lychee", mid: "Jasmine, peach, lily", base: "Vanilla, amber, musk", desc: "Sensuell och feminin orientalisk doft." },
  { brand: "Dolce & Gabbana", name: "The One Man", c: "EDT", sf: "Oriental", p: 389, top: "Grapefruit, basil", mid: "Cardamom, ginger, orange blossom", base: "Amber, tobacco, sandalwood", desc: "Karismatisk maskulin orientalisk doft." },
  { brand: "Dolce & Gabbana", name: "Light Blue Sun", c: "EDT", sf: "Citrus", p: 369, top: "Pineapple, kiwi", mid: "Jasmine, begonia", base: "Musk, white wood", desc: "Solstråledoft – sommar i en flaska." },
  { brand: "Dolce & Gabbana", name: "K", c: "EDP", sf: "Woody", p: 409, top: "Lemon, cardamom", mid: "Iris, sage", base: "Leather, sandalwood, amber", desc: "Djärv och modern lyxig herrdoft." },
  { brand: "Jimmy Choo", name: "Illicit Flower", c: "EDT", sf: "Floral", p: 329, top: "Yuzu, melon", mid: "White freesia, tuberose", base: "Musk, sandalwood", desc: "Frisk och feminin blomsterdoft." },
  { brand: "Marc Jacobs", name: "Lola", c: "EDP", sf: "Floral", p: 349, top: "Pear, red apple", mid: "Peony, violet, rose", base: "Tonka bean, sandalwood, musk", desc: "Charmig och feminin blomsterdoft." },
  { brand: "Marc Jacobs", name: "Honey", c: "EDP", sf: "Floral", p: 339, top: "Pear, honeysuckle", mid: "Peach, orange blossom, nectarine", base: "Vanilla, honey, musk", desc: "Söt honungsinspirerad blommig sommarstämning." },
  { brand: "Lancôme", name: "La Nuit Trésor", c: "EDP", sf: "Oriental", p: 419, top: "Bergamot, aldehydes", mid: "Turkish rose, black rose", base: "Vanilla, praline, musk", desc: "Passionerad nattlig orientalisk kärlek." },
  { brand: "Lancôme", name: "Miracle", c: "EDP", sf: "Floral", p: 399, top: "Lychee, ginger", mid: "Magnolia, jasmine", base: "Amber, musk, sandalwood", desc: "Optimistisk och frisk blomsterdoft." },
  { brand: "Lancôme", name: "Hypnôse", c: "EDP", sf: "Oriental", p: 409, top: "Lily, jasmine, hyacinth", mid: "Lilas, iris, rose", base: "Vanilla, patchouli, vetiver", desc: "Hypnotisk och förförisk orientalisk doft." },
  { brand: "Valentino", name: "Valentina", c: "EDP", sf: "Floral", p: 449, top: "White truffle, neroli", mid: "Gardenia, rose, jasmine", base: "Sandalwood, cashmere wood", desc: "Extravagant lyxig tryffel och gardeniadoft." },
  { brand: "Valentino", name: "Uomo Born in Roma", c: "EDP", sf: "Woody", p: 429, top: "Lavender, blueberry", mid: "Davana, iris", base: "Bourbon vanilla, woody notes", desc: "Modern och djärv maskulin doft." },
  { brand: "Givenchy", name: "Dahlia Divin", c: "EDP", sf: "Floral", p: 379, top: "Mandarin, peach", mid: "Mirabelle, jasmine", base: "Vetiver, cashmeran, musk", desc: "Sensuell och elegant dahliainspirerad doft." },
  { brand: "Givenchy", name: "Gentleman Boisée", c: "EDP", sf: "Woody", p: 389, top: "Bergamot, lemon", mid: "Iris, geranium", base: "Vetiver, patchouli, musk", desc: "Sofistikerad elegant herrdoft med träig iris." },
  { brand: "Givenchy", name: "L'Interdit Intense", c: "EDP", sf: "Floral", p: 409, top: "Pear, orange", mid: "Tuberose, jasmine", base: "Benzoin, patchouli, sandalwood", desc: "Intensiv och djärv blomsterdoft." },
  { brand: "Burberry", name: "Her", c: "EDP", sf: "Fruity", p: 369, top: "Strawberry, red currant, red apple", mid: "Jasmine, violet", base: "Musk, amber", desc: "Fruktig och feminin Londoninspirerad doft." },
  { brand: "Burberry", name: "Hero", c: "EDT", sf: "Woody", p: 379, top: "Bergamot, juniper berry", mid: "Black pepper, cedar", base: "Vetiver, oakmoss", desc: "Modig och äventyrlig herrdoft med ceder." },
  { brand: "Burberry", name: "Goddess", c: "EDP", sf: "Gourmand", p: 389, top: "Lavender", mid: "Lavender, vanilla", base: "Musk, vanilla, ethyl maltol", desc: "Söt lavendeldoft – gudinnas favoritdoft." },
  { brand: "Armani", name: "Si Passione", c: "EDP", sf: "Floral", p: 409, top: "Black currant, pear, cassis", mid: "Rose, jasmine", base: "Patchouli, vanilla, musk", desc: "Passionerad och feminin röd rosdoft." },
  { brand: "Armani", name: "Acqua di Gioia", c: "EDP", sf: "Aquatic", p: 389, top: "Lemon, aquatic notes", mid: "Peony, jasmine", base: "Sandalwood, sugar cane", desc: "Frisk havsluftsinspirerad feminin doft." },
  { brand: "Paco Rabanne", name: "Olympéa", c: "EDP", sf: "Oriental", p: 369, top: "Green mandarin, ginger", mid: "Jasmine, ambergris", base: "White musk, sandalwood, vanilla", desc: "Gudinnornas favorit – salt och sensuell." },
  { brand: "Paco Rabanne", name: "Pure XS", c: "EDP", sf: "Oriental", p: 379, top: "Ginger, mandarin", mid: "Vanilla, datura", base: "Oud, sandalwood, amber", desc: "Extrem och passionerad herrdoft." },
  { brand: "Paco Rabanne", name: "Invictus Legend", c: "EDP", sf: "Aromatic", p: 389, top: "Bay laurel, black pepper", mid: "Ambergris, jasmine", base: "Vetiver, oak, sandalwood", desc: "Legendarisk segerrik herrdoft." },
  { brand: "Hugo Boss", name: "Boss Bottled Night", c: "EDT", sf: "Oriental", p: 299, top: "Birch, cardamom", mid: "Jasmine, lavender", base: "Louro, amaranth wood", desc: "Mystisk och förförande nattlig herrdoft." },
  { brand: "Hugo Boss", name: "The Scent Absolute", c: "EDP", sf: "Gourmand", p: 349, top: "Ginger, maninka fruit", mid: "Leather accord, osmanthus", base: "Vetiver, benzoin, sandalwood", desc: "Intensiv och sensuell läckergomsdoft." },
  { brand: "Versace", name: "Crystal Noir", c: "EDP", sf: "Oriental", p: 349, top: "Pepper, ginger, cardamom", mid: "Coconut, gardenia", base: "Musk, sandalwood, civet", desc: "Mörk och mystisk exotisk nattdoft." },
  { brand: "Versace", name: "Pour Homme Dylan Blue", c: "EDT", sf: "Aquatic", p: 359, top: "Fig, grapefruit, watermelon", mid: "Violet leaf, patchouli", base: "Saffron, ambroxan, musk", desc: "Frisk och atletisk mediterran herrdoft." },
  { brand: "Versace", name: "Bright Crystal Absolu", c: "EDP", sf: "Floral", p: 369, top: "Pomegranate, yuzu", mid: "Lotus, magnolia, peony", base: "Musk, mahogany, amber", desc: "Glittrande och intens feminin blomsterdoft." },
  { brand: "Gucci", name: "Flora Gorgeous Gardenia", c: "EDP", sf: "Floral", p: 429, top: "Red berries", mid: "Gardenia, jasmine, orange blossom", base: "Sandalwood, patchouli, honey", desc: "Feminin och romantisk gardeniadoft." },
  { brand: "Gucci", name: "Memoire d'une Odeur", c: "EDP", sf: "Floral", p: 449, top: "Chamomile, Indian coral jasmine", mid: "Roman chamomile, musk", base: "Sandalwood, cedarwood, cashmeran", desc: "Könsneutral aromatisk kamomill och muskdoft." },
  { brand: "Gucci", name: "The Alchemist's Garden", c: "EDP", sf: "Woody", p: 499, top: "Bergamot, lemon", mid: "Davana, patchouli", base: "Tonka bean, musk, cedarwood", desc: "Alkemistens hemlighet – komplex träig doft." },
  { brand: "YSL", name: "Libre Intense", c: "EDP", sf: "Oriental", p: 449, top: "Bergamot, mandarin", mid: "Lavender, jasmine", base: "Musk, vanilla, amber", desc: "Intensiv frihetsdoft med lavendel och vanilj." },
  { brand: "YSL", name: "MYSLF", c: "EDP", sf: "Woody", p: 429, top: "Bergamot, cardamom, grapefruit", mid: "Magnolia, jasmine", base: "Cedarwood, vetiver, amber", desc: "Modern maskulin träig citrusdoft – fri och autentisk." },
  { brand: "Tom Ford", name: "Tobacco Vanille", c: "EDP", sf: "Oriental", p: 749, top: "Tobacco leaf, spices", mid: "Tobacco blossom, jasmine", base: "Vanilla, cacao, tonka bean", desc: "Luxuös tobaksvaniljdoft – varm och förförisk." },
  { brand: "Tom Ford", name: "Noir Extreme", c: "EDP", sf: "Oriental", p: 699, top: "Nutmeg, cardamom", mid: "Jasmine, orange blossom", base: "Amber, sandalwood, musk", desc: "Mörk och sensuell herrdoft." },
  { brand: "Tom Ford", name: "Rose Prick", c: "EDP", sf: "Floral", p: 749, top: "Coriander, pink pepper", mid: "Damask rose, Turkish rose, rose absolute", base: "Oud, sandalwood, vetiver", desc: "Djärv och dramatisk lyxrosdoft." },
  { brand: "Tom Ford", name: "Velvet Orchid", c: "EDP", sf: "Oriental", p: 729, top: "Rum, bergamot, grapefruit", mid: "Orchid, jasmine, rose", base: "Honey, amber, sandalwood", desc: "Sensuell orkidéinspirerad lyxdoft." },
  { brand: "Jo Malone", name: "Velvet Rose & Oud", c: "EDC", sf: "Oriental", p: 599, top: "Rose", mid: "Oud, sambac jasmine", base: "Sandalwood, patchouli, musk", desc: "Sensuell ros och ouddoft – koncentrerad intensitet." },
  { brand: "Jo Malone", name: "Wood Sage & Sea Salt", c: "EDC", sf: "Aquatic", p: 579, top: "Ambrette seeds, sea salt", mid: "Sage, driftwood", base: "Cardamom, sea notes", desc: "Havssaltinspirerad träig marin doft." },
  { brand: "Jo Malone", name: "Lime Basil & Mandarin", c: "EDC", sf: "Citrus", p: 569, top: "Lime, bergamot", mid: "Basil, thyme", base: "White musk, amber", desc: "Frisk och lätt citrus-basilikumdoft." },
  { brand: "Jo Malone", name: "Myrrh & Tonka", c: "EDC", sf: "Oriental", p: 589, top: "Lavender, almond", mid: "Tonka bean, myrrh", base: "Benzoin, vanilla, musk", desc: "Varm och omfamnande myrra och tonkadoft." },
  { brand: "Creed", name: "Viking", c: "EDP", sf: "Woody", p: 799, top: "Pink pepper, peppermint", mid: "Lavender, cinnamon", base: "Sandalwood, vetiver, birch", desc: "Djärv och nordisk vikingainspirerad herrdoft." },
  { brand: "Creed", name: "Love in White", c: "EDP", sf: "Floral", p: 749, top: "Nutmeg, cyclamen, iris", mid: "Rice accord, jasmine, ylang ylang", base: "Sandalwood, amber, musk", desc: "Feminin vit blommig doft." },
  { brand: "Chanel", name: "Gabrielle", c: "EDP", sf: "Floral", p: 549, top: "Mandarin, grapefruit", mid: "Jasmine, ylang ylang, grasse tuberose", base: "Sandalwood, musk, cedar", desc: "Stärkt feminin blomsterdoft – Gabrielles arv." },
  { brand: "Dior", name: "Miss Dior Blooming Bouquet", c: "EDT", sf: "Floral", p: 499, top: "Mandarin, pink pepper", mid: "Peony, rose, lily of valley", base: "White musk, patchouli", desc: "Ljus och luftig blombukettsommar." },
  { brand: "Dior", name: "Dior Homme Intense", c: "EDP", sf: "Woody", p: 529, top: "Iris, lavender", mid: "Iris, vetiver", base: "Virginia cedar, amber", desc: "Feminin och maskulin irisdoft – sofistikerad." },
  { brand: "Dior", name: "Joy", c: "EDP", sf: "Floral", p: 509, top: "Bergamot, mandarin", mid: "Rose, jasmine", base: "Sandalwood, musk", desc: "Glädjedoft – ljus, optimistisk och feminin." },
];

async function main() {
  console.log(`Seeding ${products.length} products...`);
  const slugMap = new Map<string, number>();
  let created = 0, updated = 0;

  for (const p of products) {
    const base = slugify(`${p.brand}-${p.name}`);
    const cnt = slugMap.get(base) || 0;
    const slug = cnt === 0 ? base : `${base}-${cnt}`;
    slugMap.set(base, cnt + 1);
    const baseSku = makeSku(p.brand, p.name);
    const sku = cnt === 0 ? baseSku : `${baseSku}-${cnt}`;
    const stock = rand(0, 50);
    try {
      const ex = await prisma.product.findUnique({ where: { sku } });
      await prisma.product.upsert({
        where: { sku },
        update: { slug, name: p.name, brand: p.brand, description: p.desc || "", price: p.p, sizeMl: 10, concentration: p.c, scentFamily: p.sf, topNotes: p.top || "", middleNotes: p.mid || "", baseNotes: p.base || "", images: "[]", stock, available: stock > 0, categories: '["parfym","pocket-parfym"]', tags: JSON.stringify([p.sf.toLowerCase(), p.c.toLowerCase()]) },
        create: { sku, slug, name: p.name, brand: p.brand, description: p.desc || "", price: p.p, currency: "SEK", sizeMl: 10, concentration: p.c, scentFamily: p.sf, topNotes: p.top || "", middleNotes: p.mid || "", baseNotes: p.base || "", images: "[]", stock, available: stock > 0, categories: '["parfym","pocket-parfym"]', tags: JSON.stringify([p.sf.toLowerCase(), p.c.toLowerCase()]), sourceUrl: "" },
      });
      ex ? updated++ : created++;
    } catch (e) { console.error(`Error: ${p.brand} ${p.name}`, e); }
  }
  const total = await prisma.product.count();
  console.log(`Done! Created: ${created}, Updated: ${updated}, Total: ${total}`);
}

main().catch(console.error).finally(() => prisma.$disconnect());
